<a href="https://colab.research.google.com/github/hulkavocado/data_science_bootcamp/blob/main/01_wprowadzenie_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('hello colab')

hello colab


In [2]:
import numpy as np
np.__version__

'1.21.5'

In [6]:
x = np.array([[-1,3],[2,0]])
y= np.array([[2,3], [3,4]])

print(x, '\n')
print(y)



[[-1  3]
 [ 2  0]] 

[[2 3]
 [3 4]]


In [7]:
np.dot (x,y)

array([[7, 9],
       [4, 6]])

In [8]:
np.random.seed(0)

In [11]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [14]:
np.random.rand(10, 2)

array([[0.36872517, 0.82099323],
       [0.09710128, 0.83794491],
       [0.09609841, 0.97645947],
       [0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145]])

In [18]:
np.random.randint(low=100, high=200, size = 10)

array([114, 141, 158, 165, 136, 110, 186, 143, 111, 102])

In [21]:
np.random.choice([1, 2, 2, 3])

3

In [22]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [25]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.random.shuffle(data)

In [27]:
data

array([1, 4, 7, 5, 2, 3, 8, 9, 6, 0])

In [29]:
np.exp(2)

7.38905609893065

In [30]:
np.sqrt(9)

3.0

In [32]:
np.all([1, 1, 1])

True

In [35]:
np.any ([0, 1, 0])

True

In [37]:
bool(5)

True

In [39]:
A = np.random.rand(5)
A

array([0.59204193, 0.57225191, 0.22308163, 0.95274901, 0.44712538])

In [40]:
np.argmax(A)

3

In [42]:
A[np.argmax(A)]

0.952749011516985

In [43]:
np.argsort(A)

array([2, 4, 1, 0, 3])

In [45]:
np.max(A)

0.952749011516985

In [46]:
A = np.arange(20)

In [47]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
A[:2]

array([0, 1])

In [51]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
A[:, 0]

array([ 0,  5, 10, 15])

In [54]:
A[1,1]

6

In [56]:
A[1, 4]

9

In [58]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [63]:
for row in A:
  print (row[:2])

[0 1]
[5 6]
[10 11]
[15 16]


In [64]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [65]:
A.shape

(4, 5)

In [66]:
A.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [68]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [70]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [71]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [73]:
A= np.arange(start = -10, stop = 10, step= 0.5)

In [74]:
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [75]:
A = A.reshape(10,-1)

In [76]:
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [77]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [78]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])